checkpoint: true
event_classes:
- cc_nue
- cc_numu
- cc_nutau
- nc
event_head: false
filter_head: true
in_features: 4
lr: 0.001
nexus_features: 16
num_iters: 5
planar_features: 64
planes:
- u
- v
- y
semantic_classes:
- MIP
- HIP
- shower
- michel
- diffuse
semantic_head: true
vertex_aggr: lstm
vertex_head: false
vertex_lstm_features: 32
vertex_mlp_features:
- 32
